### ISSUE TITLE
Compatability issues with recast

### ISSUE THREAD

**Issue by leumasme** [goto-bus-stop/scope-analyzer#25]
Recast is a AST modification library that is focused towards minimizing the difference between your input code and output code.
Thus, parsing code with recast to AST and then instantly printing it to code again should produce the same output as the input.
(As far as i read, this is done via a readonly shadow AST which is diff'd with the writable AST)

This does not work when using scope-analyzer with a recast AST.
 As soon as 
 ```
 const scan = require("scope-analyzer");
 scan.analyze(ast)
 ```
 is called, the output AST will be completely reformatted, as if every line was changed.
 
 Demo:
 ```
 let ast = recast.parse(readFileSync(`samples/${filename}.js`).toString())
 scan.analyze(ast) // If this line is not commented out, the entire code will be reformatted
 writeFileSync(`./out.js`, recast.print(ast).code)
 ```

**Comment by goto-bus-stop** [comment]
this lribrary adds a Symbol property to each node for scope information. maybe making it non-enumerable would already be enough to appease recast. otherwise we could use a WeakMap so we don't need to touch the nodes at all.

**Comment by goto-bus-stop** [comment]
📦 2.1.2

making it non-enumerable makes it work with recast. it's a significant 20-30% performance penalty in my unscientific benchmarks (i guess a plain `node.scope = scope` makes the optimizer happier than this `defineProperty` stuff) but using a WeakMap was even worse.
